events {}

http {

  upstream app_um_frontend {
    server app_um_frontend:5173;
  }

  upstream app_um_backend {
    server app_um_backend:3000;
  }

  upstream app_dois_frontend {
    server app_dois_frontend:5173;
  }

  upstream app_dois_backend {
    server app_dois_backend:3001;
  }

  server {
    listen 70;
    server_name app1.localhost;

    location / {
      proxy_pass http://app_um_frontend;
      proxy_set_header Host $host;
    }

    location /backend/ {
      proxy_pass http://app_um_backend/;
      proxy_set_header Host $host;
    }
  }

  server {
    listen 70;
    server_name app2.localhost;

    location / {
      proxy_pass http://app_dois_frontend;
      proxy_set_header Host $host;
    }

    location /backend/ {
      proxy_pass http://app_dois_backend/;
      proxy_set_header Host $host;
    }
  }
}