version: "3.9"

services:
  backend:
    build: ./backend
    container_name: app_dois_backend
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=/backend
    container_name: app_dois_frontend
    ports:
      - "6051:5173"
    depends_on:
      - backend